{
  "hash": "8af5c640d22afccc7af991b7ced04e7f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Lingxuan Gao\"\ndate: Oct 13th\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\n\n# Load spatial data\npa_counties <- st_read(\"./data/Pennsylvania_County_Boundaries.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `D:\\MUSA\\MUSA_5080\\portfolio-setup-LingxuanGao\\labs\\lab_2\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\ndistricts <- st_read(\"data/districts.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `U.S._Congressional_Districts_for_Pennsylvania' from data source \n  `D:\\MUSA\\MUSA_5080\\portfolio-setup-LingxuanGao\\labs\\lab_2\\data\\districts.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 17 features and 8 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -80.51939 ymin: 39.71986 xmax: -74.68956 ymax: 42.26935\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(\"data/hospitals.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `D:\\MUSA\\MUSA_5080\\portfolio-setup-LingxuanGao\\labs\\lab_2\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |=======                                                               |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================|  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n  223\n- How many census tracts?\n  3445\n- What coordinate reference system is each dataset in?\n  census_tracts: EPSG:4269\n  districts: EPSG:4326\n  hospitals: EPSG:4326\n  pa_counties: EPSG:3857\n  \n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\nacs_vars <- c(\n  total_pop = \"B01003_001\",        \n  median_income = \"B19013_001\", \n  age65_over_male = \"B01001_020\",  \n  age65_over_female = \"B01001_044\" \n)\n\npa_acs <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = acs_vars,\n  year = 2022,\n  geometry = TRUE,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |============================                                          |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\npa_acs <- pa_acs %>%\n  mutate(\n    pop_65plus = age65_over_maleE + age65_over_femaleE,\n    pct_65plus = pop_65plus / total_popE * 100\n  )\n\n# Join to tract boundaries\npa_acs_sf <- st_transform(pa_acs, 4326)\nsum(is.na(pa_acs_sf$median_incomeE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 63\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(pa_acs_sf$median_incomeE, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70188\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n  2022\n- How many tracts have missing income data?\n  63\n- What is the median income across all PA census tracts?\n  70188\n  \n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n# Define vulnerability thresholds\nincome_threshold <- quantile(pa_acs_sf$median_incomeE, 0.2, na.rm = TRUE)\nelderly_threshold <- quantile(pa_acs_sf$pct_65plus, 0.8, na.rm = TRUE)\n\ncat(\"Income threshold:\", round(income_threshold, 0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIncome threshold: 51725 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Elderly population threshold:\", round(elderly_threshold, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nElderly population threshold: 3.6 %\n```\n\n\n:::\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on criteria\nvulnerable_tracts <- pa_acs_sf %>%\n  mutate(\n    is_low_income = median_incomeE <= income_threshold,\n    is_elderly = pct_65plus >= elderly_threshold,\n    vulnerable = ifelse(is_low_income & is_elderly, 1, 0)\n  )\n\n# Summary\nnum_vulnerable <- sum(vulnerable_tracts$vulnerable, na.rm = TRUE)\ntotal_tracts <- nrow(vulnerable_tracts)\npct_vulnerable <- num_vulnerable / total_tracts * 100\n\ncat(\"Number of vulnerable tracts:\", num_vulnerable, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of vulnerable tracts: 119 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Percentage of all PA tracts:\", round(pct_vulnerable, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of all PA tracts: 3.45 %\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n  I chose the 20th percentile of the statewide median household income as the low-income threshold.This aligns with the Pareto principle (80/20 rule).\n  \n- What elderly population threshold did you choose and why?\n  I chose the 80th percentile of the percentage of population aged 65 and over as the threshold for defining elderly concentration. This aligns with the Pareto principle (80/20 rule).\n  \n- How many tracts meet your vulnerability criteria?\n  119\n- What percentage of PA census tracts are considered vulnerable by your definition?\n  3.45 %\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nvulnerable_tracts_proj <- st_transform(vulnerable_tracts, 5070)\nhospitals_proj <- st_transform(hospitals, 5070)\n\n# Calculate distance from each tract centroid to nearest hospital\ntract_centroids <- st_centroid(vulnerable_tracts_proj)\n\ndist_matrix <- st_distance(tract_centroids, hospitals_proj)  # in meters\nnearest_hospital_dist <- apply(dist_matrix, 1, min)  # get min distance per tract\n\n# Add distances (converted to miles)\nvulnerable_tracts_proj$dist_to_hospital_mi <- as.numeric(nearest_hospital_dist) / 1609.34\n\n# Summarize results\navg_dist <- mean(vulnerable_tracts_proj$dist_to_hospital_mi, na.rm = TRUE)\nmax_dist <- max(vulnerable_tracts_proj$dist_to_hospital_mi, na.rm = TRUE)\nover_15mi <- sum(vulnerable_tracts_proj$dist_to_hospital_mi > 15, na.rm = TRUE)\n\ncat(\"Average distance to nearest hospital (miles):\", round(avg_dist, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage distance to nearest hospital (miles): 4.41 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Maximum distance to nearest hospital (miles):\", round(max_dist, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMaximum distance to nearest hospital (miles): 32.69 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of vulnerable tracts >15 miles from hospital:\", over_15mi, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of vulnerable tracts >15 miles from hospital: 130 \n```\n\n\n:::\n\n```{.r .cell-code}\n# I use EPSG:5070 (CONUS Albers) for a single, statewide projection. It keeps linear distortion small at Pennsylvania’s scale while avoiding UTM zone splits, making nearest-hospital distance comparisons and thresholds robust and reproducible.\n```\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n  4.41 miles\n- What is the maximum distance?\n  32.69 miles\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n  130\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(\n    underserved = ifelse(vulnerable == 1 & dist_to_hospital_mi > 15, 1, 0)\n  )\n\nnum_underserved <- sum(vulnerable_tracts_proj$underserved, na.rm = TRUE)\nnum_vulnerable <- sum(vulnerable_tracts_proj$vulnerable, na.rm = TRUE)\npct_underserved <- num_underserved / num_vulnerable * 100\n\ncat(\"Number of underserved tracts:\", num_underserved, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of underserved tracts: 4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Percentage of vulnerable tracts that are underserved:\", round(pct_underserved, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of vulnerable tracts that are underserved: 3.36 %\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n  4\n- What percentage of vulnerable tracts are underserved?\n  3.36%\n- Does this surprise you? Why or why not?\n  No. Although some rural parts of Pennsylvania are geographically remote, the majority of the population lives in urban and suburban regions where hospitals are relatively dense. Therefore, only a small share of vulnerable tracts (about 3.36%) are more than 15 miles away from a hospital.\n  \n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\nlibrary(dplyr)\npa_counties <- st_transform(pa_counties, 5070)\nvul_with_county <- st_join(vulnerable_tracts_proj, pa_counties, join = st_intersects)\n\n# Aggregate statistics by county\ncounty_summary <- vul_with_county %>%\n  st_drop_geometry() %>%  \n  group_by(COUNTY_NAM) %>% \n  summarise(\n    n_vulnerable = sum(vulnerable, na.rm = TRUE),\n    n_underserved = sum(underserved, na.rm = TRUE),\n    pct_underserved = ifelse(n_vulnerable > 0, (n_underserved / n_vulnerable) * 100, NA),\n    avg_dist_mi = mean(dist_to_hospital_mi, na.rm = TRUE),\n    total_vulnerable_pop = sum(total_popE[vulnerable == 1], na.rm = TRUE)\n  ) %>%\n  arrange(desc(pct_underserved))\n\ntop5_pct <- head(county_summary, 5)\n\ncat(\"Top 5 counties with highest % of underserved vulnerable tracts:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 5 counties with highest % of underserved vulnerable tracts:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(top5_pct[, c(\"COUNTY_NAM\", \"pct_underserved\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  COUNTY_NAM pct_underserved\n  <chr>                <dbl>\n1 FRANKLIN               100\n2 JUNIATA                100\n3 MIFFLIN                100\n4 MONROE                 100\n5 PERRY                  100\n```\n\n\n:::\n\n```{.r .cell-code}\ntop_vulnerable_pop <- vul_with_county %>%\n  filter(underserved == 1) %>%\n  group_by(COUNTY_NAM) %>%\n  summarise(vulnerable_far_pop = sum(total_popE, na.rm = TRUE)) %>%\n  arrange(desc(vulnerable_far_pop)) \n```\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n  FRANKLIN, JUNIATA, MIFFLIN, MONROE and PERRY.\n- Which counties have the most vulnerable people living far from hospitals?\n  CRAWFORD, FRANKLIN, HUNTINGDON, JUNIATA, MIFFLIN\n- Are there any patterns in where underserved counties are located?\n  Underserved counties are primarily located in central to western Pennsylvania’s rural belt, particularly along the Appalachian Mountain region (e.g., Franklin, Juniata, Mifflin, Huntingdon) and parts of the northeastern fringe (e.g., Monroe and Perry). These areas tend to have low population density, challenging topography, and limited transportation infrastructure, which increase travel distances to the nearest hospitals. \n  \n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nlibrary(knitr)\nlibrary(scales)\n\npriority_table <- county_summary %>%\n  arrange(desc(pct_underserved), desc(total_vulnerable_pop)) %>%\n  select(\n    County = COUNTY_NAM,\n    `Vulnerable Tracts` = n_vulnerable,\n    `Underserved Tracts` = n_underserved,\n    `% Underserved` = pct_underserved,\n    `Avg Distance to Hospital (mi)` = avg_dist_mi,\n    `Total Vulnerable Population` = total_vulnerable_pop\n  ) %>%\n  mutate(\n    `% Underserved` = round(`% Underserved`, 2),\n    `Avg Distance to Hospital (mi)` = round(`Avg Distance to Hospital (mi)`, 1),\n    `Total Vulnerable Population` = comma(`Total Vulnerable Population`)\n  ) %>%\n  head(10)\n\n# Display formatted table\nkable(\n  priority_table,\n  caption = \"Top 10 Priority Counties for Healthcare Investment in Pennsylvania\",\n  align = \"lccccc\",\n  format.args = list(big.mark = \",\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Priority Counties for Healthcare Investment in Pennsylvania\n\n|County     | Vulnerable Tracts | Underserved Tracts | % Underserved | Avg Distance to Hospital (mi) | Total Vulnerable Population |\n|:----------|:-----------------:|:------------------:|:-------------:|:-----------------------------:|:---------------------------:|\n|FRANKLIN   |         1         |         1          |    100.00     |              5.9              |            1,782            |\n|JUNIATA    |         1         |         1          |    100.00     |             14.7              |            1,782            |\n|MIFFLIN    |         1         |         1          |    100.00     |              8.7              |            1,782            |\n|PERRY      |         1         |         1          |    100.00     |             11.3              |            1,782            |\n|MONROE     |         1         |         1          |    100.00     |             10.3              |            1,299            |\n|SULLIVAN   |         1         |         1          |    100.00     |             16.8              |             918             |\n|HUNTINGDON |         2         |         1          |     50.00     |              9.1              |            5,111            |\n|LYCOMING   |         2         |         1          |     50.00     |              6.3              |            4,094            |\n|COLUMBIA   |         2         |         1          |     50.00     |              6.5              |            3,446            |\n|LUZERNE    |         3         |         1          |     33.33     |              5.2              |           10,055            |\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n# Merge geometry back to county summary\npa_counties_5070 <- st_transform(pa_counties, 5070)\n\ncounty_map <- pa_counties_5070 %>%\n  left_join(county_summary, by = c(\"COUNTY_NAM\"))\n\n# Create choropleth\nggplot() +\n  geom_sf(data = county_map, aes(fill = pct_underserved), color = \"white\", size = 0.2) +\n  geom_sf(data = hospitals_proj, color = \"blue\", size = 0.5, alpha = 0.6) +\n  scale_fill_gradient(\n    name = \"% of Vulnerable Tracts Underserved\",\n    low = \"#fee8c8\", high = \"#e34a33\",\n    na.value = \"gray90\",\n    labels = function(x) paste0(round(x, 1), \"%\")\n  ) +\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Percentage of Vulnerable Census Tracts that are Underserved, by County\",\n    caption = \"Data sources: U.S. Census ACS 2022, Pennsylvania Hospital Locations\\nProjection: NAD83 / Conus Albers Equal Area (EPSG:5070)\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(size = 16, face = \"bold\"),\n    plot.subtitle = element_text(size = 12),\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text = element_text(size = 9),\n    plot.caption = element_text(size = 8, hjust = 0)\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/County-Level Choropleth-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nggplot() +\n  geom_sf(data = pa_counties_5070, fill = \"gray98\", color = \"gray80\", size = 0.2) +\n\n  geom_sf(data = vulnerable_tracts_proj, aes(fill = factor(vulnerable)), \n          color = NA, alpha = 0.4, show.legend = FALSE) +\n\n  geom_sf(data = subset(vulnerable_tracts_proj, underserved == 1), \n          fill = \"#d7301f\", color = \"white\", size = 0.15) +\n\n  geom_sf(data = hospitals_proj, color = \"#045a8d\", size = 0.6, alpha = 0.8) +\n\n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania\",\n    subtitle = \"Tracts with low income and high elderly population located more than 15 miles from the nearest hospital\",\n    caption = \"Data sources: U.S. Census ACS 2022, Pennsylvania Hospital Locations\\nProjection: NAD83 / CONUS Albers Equal Area (EPSG:5070)\"\n  ) +\n  \n  theme_void() +\n  theme(\n    plot.title = element_text(size = 16, face = \"bold\"),\n    plot.subtitle = element_text(size = 12),\n    plot.caption = element_text(size = 8, hjust = 0),\n    legend.position = \"none\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/Detailed Vulnerability Map-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nggplot(vulnerable_tracts_proj, aes(x = dist_to_hospital_mi)) +\n  geom_histogram(\n    fill = \"#3182bd\", color = \"white\", bins = 30, alpha = 0.8\n  ) +\n  geom_vline(aes(xintercept = mean(dist_to_hospital_mi, na.rm = TRUE)),\n             color = \"red\", linetype = \"dashed\", size = 1) +\n  labs(\n    title = \"Distribution of Distance to Nearest Hospital for Vulnerable Tracts\",\n    subtitle = \"Red dashed line shows mean distance across all vulnerable census tracts\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Number of Vulnerable Tracts\",\n    caption = \"Data: ACS 2022, Pennsylvania Hospital Locations\\nProjection: EPSG 5070\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(size = 11),\n    plot.caption = element_text(size = 8, hjust = 0),\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nschools <- st_read(\"./data/Schools.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Schools' from data source \n  `D:\\MUSA\\MUSA_5080\\portfolio-setup-LingxuanGao\\labs\\lab_2\\data\\Schools.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 495 features and 14 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.2665 ymin: 39.90781 xmax: -74.97057 ymax: 40.12974\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncrimes  <- st_read(\"./data/incidents_part1_part2/incidents_part1_part2.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `incidents_part1_part2' from data source \n  `D:\\MUSA\\MUSA_5080\\portfolio-setup-LingxuanGao\\labs\\lab_2\\data\\incidents_part1_part2\\incidents_part1_part2.shp' \n  using driver `ESRI Shapefile'\nreplacing null geometries with empty geometries\nSimple feature collection with 151197 features and 13 fields (with 890 geometries empty)\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.2753 ymin: 39.87731 xmax: -74.95981 ymax: 40.13646\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nbike_network <- st_read(\"./data/Bike_Network.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Bike_Network' from data source \n  `D:\\MUSA\\MUSA_5080\\portfolio-setup-LingxuanGao\\labs\\lab_2\\data\\Bike_Network.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 5225 features and 8 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: -75.26927 ymin: 39.87528 xmax: -74.96572 ymax: 40.124\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(crimes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(bike_network)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nschools_2272 <- st_transform(schools, 2272)\ncrimes_2272 <- st_transform(crimes, 2272)\nbike_network_2272 <- st_transform(bike_network, 2272)\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n  I selected the Schools, Crime Incidents, and Bike Network datasets for Philadelphia to analyze safety conditions within 1000-ft school zones and the availability of bicycle infrastructure. This analysis helps identify areas where students may face higher crime risk and limited safe travel options, supporting Safe Routes to School policy planning.\n- What is the data source and date?\n  All datasets were obtained from OpenDataPhilly.\n- How many features does it contain?\n  Schools: ≈ 300 points\n  Crime Incidents: ≈ 150000 records\n  Bike Network: ≈ 5000 road segments\n- What CRS is it in? Did you need to transform it?\n  All three datasets were originally in WGS 84 (EPSG 4326) with units in degrees. They were transformed to EPSG 2272 (Pennsylvania State Plane South, US Feet) to ensure accurate distance and buffer calculations.\n  \n---\n\n2. **Pose a research question**\n\nWhich school zones in Philadelphia face both high crime rates and limited bicycle infrastructure, indicating a need for targeted ‘Safe Routes to School’ interventions?\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n\nschools_2272 <- schools_2272 %>%\n  mutate(school_id = row_number())\n\nschool_buffer <- st_buffer(schools_2272, dist = 304.8)\n\ncrimes_joined <- st_join(crimes_2272, school_buffer, join = st_within, left = FALSE)\n\ncrime_summary <- crimes_joined %>%\n  st_drop_geometry() %>%\n  group_by(school_id) %>%\n  summarise(crime_count = n(), .groups = \"drop\")\n\nsafety_summary <- school_buffer %>%\n  left_join(crime_summary, by = \"school_id\") %>%\n  mutate(\n    crime_count = replace_na(crime_count, 0),\n    risk_level = case_when(\n      crime_count >= quantile(crime_count, 0.75) ~ \"High Risk\",\n      crime_count >= quantile(crime_count, 0.25) ~ \"Moderate Risk\",\n      TRUE ~ \"Low Risk\"\n    ),\n    has_bike_lane = lengths(st_intersects(., bike_network_2272)) > 0\n  )\n\nlibrary(knitr)\nkable(\n  safety_summary %>%\n    st_drop_geometry() %>%\n    select(school_name, crime_count, has_bike_lane, risk_level) %>%\n    arrange(desc(crime_count)) %>%\n    head(10),\n  caption = \"Top 10 Schools by Crime Count within 1000-ft Safety Zones\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Schools by Crime Count within 1000-ft Safety Zones\n\n|school_name                  | crime_count|has_bike_lane |risk_level |\n|:----------------------------|-----------:|:-------------|:----------|\n|FREIRE CHARTER SCHOOL        |         236|TRUE          |High Risk  |\n|K012 KIDS SCHOOL             |         191|TRUE          |High Risk  |\n|VISITATION SCHOOL            |         177|TRUE          |High Risk  |\n|ROMAN CATHOLIC HIGH SCHOOL   |         150|FALSE         |High Risk  |\n|JUNIATA PARK ACADEMY         |         118|TRUE          |High Risk  |\n|TECH FREIRE CHARTER SCHOOL   |         109|FALSE         |High Risk  |\n|GIRLS, PHILA HIGH SCHOOL FOR |         107|TRUE          |High Risk  |\n|SCIENCE LEADERSHIP ACADEMY   |         103|TRUE          |High Risk  |\n|WRIGHT, RICHARD R. SCHOOL    |          98|FALSE         |High Risk  |\n|YES PHILLY                   |          93|TRUE          |High Risk  |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter: only high-risk schools without nearby bike lanes\nhighrisk_nobike <- safety_summary %>%\n  filter(risk_level == \"High Risk\" & has_bike_lane == FALSE)\n\nlibrary(sf)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(here)\n\npa_tracts <- st_read(\"./data/PA-tracts.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PA-tracts' from data source \n  `D:\\MUSA\\MUSA_5080\\portfolio-setup-LingxuanGao\\labs\\lab_2\\data\\PA-tracts.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 3217 features and 398 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -80.51989 ymin: 39.7198 xmax: -74.68952 ymax: 42.26986\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nphilly_tracts <- pa_tracts %>%\n  filter(pl == \"Philadelphia County, Pennsylvania\")\n\nphilly_tracts_2272 <- st_transform(philly_tracts, 2272)\n\n\nplot(st_geometry(philly_tracts_2272))\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = philly_tracts_2272, fill = NA, color = \"gray40\", size = 0.1) +\n  \n  geom_sf(data = bike_network_2272, color = \"#74c476\", size = 0.3, alpha = 0.5) +\n  \n  geom_sf(data = highrisk_nobike, fill = \"#cb181d\", color = \"#cb181d\", size = 0.6, alpha = 1) +\n  \n  geom_sf(data = schools_2272, color = \"black\", fill = \"black\", size = 0.3, shape = 21) +\n  \n  labs(\n    title = \"High-Risk Schools without Bike Lanes in Philadelphia County\",\n    subtitle = \"Tracts within the Philadelphia County boundary\",\n    caption = \"Data: OpenDataPhilly & Eviction Lab (2024) | CRS: EPSG 2272 | Analysis by Lingxuan Gao\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 15, hjust = 0.5),\n    plot.subtitle = element_text(size = 11, hjust = 0.5),\n    plot.caption = element_text(size = 9, color = \"gray40\", hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\n[The map shows that high-risk schools without nearby bike lanes are scattered across Philadelphia County, with notable clusters in Central Philadelphia and the southern parts of North Philadelphia. A smaller number of red points also appear in West Philadelphia and South Philadelphia, indicating that safety and bike infrastructure gaps are not limited to any single district. Overall, most schools with higher crime counts are located along major urban corridors, where dense street networks and limited bike lanes may increase exposure to unsafe environments.]\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n\n**File naming:** `LastName_FirstName_Assignment2.html` and `LastName_FirstName_Assignment2.qmd`\n\n---\n\n",
    "supporting": [
      "assignment2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}